services:

  spark-master:
    image: apache/spark:3.5.7
    container_name: spark-master
    env_file:
      - .env
    ports:
      - '${SPARK_MASTER_UI_PORT}:8080'
      - '${SPARK_MASTER_PORT}:7077'
    environment:
      - SPARK_MASTER_HOST=${SPARK_MASTER_HOST}
      - SPARK_DRIVER_MEMORY=${SPARK_DRIVER_MEMORY}
      - SPARK_RPC_MESSAGE_MAXSIZE=${SPARK_RPC_MESSAGE_MAXSIZE}
      - SPARK_DRIVER_MAXRESULTSIZE=${SPARK_DRIVER_MAXRESULTSIZE}
    volumes:
      - ${SPARK_JOBS_PATH}:/opt/spark/spark_jobs
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    hostname: spark-master
    networks:
      - spark-net

  spark-worker-1:
    image: apache/spark:3.5.7
    container_name: spark-worker-1
    env_file:
      - .env
    environment:
      - SPARK_WORKER_MEMORY=${SPARK_WORKER_MEMORY}
      - SPARK_WORKER_CORES=${SPARK_WORKER_CORES}
      - SPARK_RPC_MESSAGE_MAXSIZE=${SPARK_RPC_MESSAGE_MAXSIZE}
    depends_on:
      - spark-master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    hostname: spark-worker-1
    networks:
      - spark-net

  spark-worker-2:
    image: apache/spark:3.5.7
    container_name: spark-worker-2
    env_file:
      - .env
    environment:
      - SPARK_WORKER_MEMORY=${SPARK_WORKER_MEMORY}
      - SPARK_WORKER_CORES=${SPARK_WORKER_CORES}
      - SPARK_RPC_MESSAGE_MAXSIZE=${SPARK_RPC_MESSAGE_MAXSIZE}
    depends_on:
      - spark-master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    hostname: spark-worker-2
    networks:
      - spark-net


  airflow:
    image: apache/airflow:3.0.1
    build: .
    container_name: airflow-standalone
    env_file:
      - .env
    environment:
      - AIRFLOW__CORE__EXECUTOR=${AIRFLOW_EXECUTOR}
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      - AIRFLOW__CORE__LOAD_EXAMPLES=${AIRFLOW_LOAD_EXAMPLES}
      - _AIRFLOW_DB_UPGRADE=true
      - _AIRFLOW_WWW_USER_CREATE=true
      - _AIRFLOW_WWW_USER_USERNAME=${AIRFLOW_ADMIN_USERNAME}
      - _AIRFLOW_WWW_USER_PASSWORD=${AIRFLOW_ADMIN_PASSWORD}
      - PYTHONPATH=/opt/airflow
    ports:
      - "${AIRFLOW_WEB_PORT}:8080"
    volumes:
      - ${DAGS_PATH}:/opt/airflow/dags
      - ${SPARK_JOBS_PATH}:/opt/airflow/spark_jobs
    command: bash -c "airflow db migrate && airflow users create --username ${AIRFLOW_ADMIN_USERNAME} --password ${AIRFLOW_ADMIN_PASSWORD} --firstname ${AIRFLOW_ADMIN_FIRSTNAME} --lastname ${AIRFLOW_ADMIN_LASTNAME} --role Admin --email ${AIRFLOW_ADMIN_EMAIL} && airflow webserver & airflow scheduler"
    depends_on:
      - spark-master
    networks:
      - spark-net

networks:
  spark-net:
    driver: bridge
